a = ("nigga ..... ?????? nigga")
print(a.upper())
print(a.lower())
print(a.rstrip(".?"))
print(a.replace("nigga", "rehman"))
print(a.split(" "))
blog = ("welcOME To Our WEBSITE")
print(blog.capitalize())
b = ("strings")
print(b.center(109))
print(a.count("nigga"))
print(a.endswith("nigga"))
c = ("ali is a good guy , and he likes to play cricket")
print(c.find("cricket"))
print(c.find("criciiii"))
d = ("NIGGagigga7877")
print(d.isalnum())
d2 = ("GigganiggA")
print(d2.isalpha())
print(d2.islower())
print(d2.isprintable())
print(d2.isspace())
d3 = ("To Kill A Mocking Bird")
print(d3.istitle())
print(d3.isupper())
print(a.startswith("!"))
print(d3.swapcase())
print(d3.title())